name: C Code Testing and Deployment Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install GCC and Required Tools
      - name: Install GCC and Required Tools
        run: sudo apt-get update && sudo apt-get install -y build-essential

      # Step 3: Compile the code
      - name: Compile main.c
        run: gcc -o main main.c -Wall

      # Step 4: Run the program
      - name: Run main.c Program
        run: ./main

      # Step 5: Add Host Key to Known Hosts
      - name: Add Hostinger Host Key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 65002 217.196.55.186 >> ~/.ssh/known_hosts

      # Step 6: Deploy to Hostinger via SSH
      - name: Deploy main.c to Hostinger
        if: success()
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$SSH_KEY" > private_key
          chmod 600 private_key
          scp -P 65002 -i private_key main.c u691780200@217.196.55.186:/home/u691780200/public_html/
          rm private_key
