name: Deploy main.c to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v3

      # Step 2: Compile and Run main.c
      - name: Build and Test main.c
        run: |
          gcc -o main main.c -Wall
          ./main

      # Step 3: Deploy to Hostinger
      - name: Deploy to Hostinger
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$SSH_KEY" > private_key
          chmod 600 private_key
          mkdir -p ~/.ssh
          ssh-keyscan -p 65002 217.196.55.186 >> ~/.ssh/known_hosts
          scp -P 65002 -i private_key main.c u691780200@217.196.55.186:/home/u691780200/public_html/
          rm private_key
