name: C Code Testing Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install GCC and Required Tools
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Compile main.c
        run: gcc -o main main.c -Wall

      - name: Run main.c Program
        run: ./main

